<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovieTracker.Data.Models\MovieTracker.Data.Models.csproj" />
    <ProjectReference Include="..\MovieTracker.Data\MovieTracker.Data.csproj" />
    <ProjectReference Include="..\MovieTracker.ViewModels\MovieTracker.ViewModels.csproj" />
  </ItemGroup>

</Project>
